### ISSUE TITLE
Joy232 on Sony HB-55P

### ISSUE THREAD

**Issue by ghost** [Danjovic/Joy232#1]
Hello,

First of all thanks for your work. It was just a coincidence that I was in need of serial communication and you updated the project!

I'm trying to replicate your work using a USB to TTL device. The hook apparently works perfectly as the led the device has blinks when I do a LPRINT. However it doesn't shows any text. Could it be due to baud speed adjustment for the different models?

Thanks for your support!

**Comment by ghost** [comment]
It was a silly error. I interchanged TX with RX. 

It works like a charm!

**Comment by Danjovic** [comment]
Thanks for the feedback! In which machine did you tested the code?

**Comment by ghost** [comment]
I tested it with my sony hitbit 55P with a Megaflashrom cartridge. The connection was done with a USB yo TTL device.

Do you think full duplex bidirectiona communication is doable? It would be great for a project I have.

Thanks!

**Comment by Danjovic** [comment]
I think that Reception is possible, though it might require RTS/CTS flow control to work. Have wrote some code a long time ago but never tested ([link](http://hotbit.blogspot.com.br/2008/02/rx232-primeira-verso-compilvel.html))

**Comment by ghost** [comment]
One friend send me this: http://map.grauw.nl/resources/joynet/ So there are already things done. 
I will also test this as soon as I can. If you're interested on results I can come back when I have them.

Thanks!

**Comment by Danjovic** [comment]
I have heard about joynet but never tried it. Nevertheless other protocols are possible for using with joystick port notably I2C and SPI.
